Corrections, clarifications and general fixes to docs
CoderLine/alphaTabWebsite pull request #56
Opened 2022-03-17 19:00 UTC by jonaro00

I went through all documentation files in `alphatex`, `getting-started` and `tutorial-web` and fixed stuff: Corrections, clarifications, simplifications of some examples, punctuation, consistency.
Among the changes are backslashes that remove the leading newline in the alphaTex code examples, saving some vertical space.
Before: 
![image](https://user-images.githubusercontent.com/54029719/158873892-8b01d282-0b68-45e1-bc1c-a056ca1c5e30.png)
After: 
![image](https://user-images.githubusercontent.com/54029719/158873992-a37c3f57-8292-4b32-a797-23a94f76df7c.png)

2022-03-17 19:39 UTC, Danielku15 requested changes
Thanks a lot of taking the time to proof-read all these docs. Being not a native speaker and maybe sometimes lazy when it comes to docs easily degrade the quality of such docs. Having more people contributing there helps a lot. 

Some remarks regarding your changes though.

2022-03-17 19:39 UTC, Danielku15 commented on docs/alphatex/bar-metadata.mdx
> +<AlphaTexSample>{`\
Are those backslashes intentional? Feels unnecessary to me.

2022-03-17 19:39 UTC, Danielku15 commented on docs/alphatex/tracks-staves.mdx
> +\\track "Second" // new track
Leaving out the track name here was intentional to indicate that it is optional.

2022-03-17 19:39 UTC, Danielku15 commented on docs/alphatex/tracks-staves.mdx
> +\\tuning D2 A2 D3 G3 B3 E4 // tuning of new track
Also here it was intentional to have an additional string to show a difference between the two tracks on the number of strings.

2022-03-17 19:39 UTC, Danielku15 commented on docs/contributing.mdx
> -* `build-csharp` - compiles a C#/.net version of alphaTab using the current code state
The ordering in this list was intentional to be rather grouped by platform than being alphabetical or grouped by type.

2022-03-17 19:39 UTC, Danielku15 commented on docs/tutorial-web/player.mdx
> +4. We add some UI elements for the user to play/pause the playback and show the current position.
I think this should stay "start". We "start" the playback, but we do not "play the playback".

2022-03-17 20:45 UTC, jonaro00 commented on docs/alphatex/bar-metadata.mdx
> +<AlphaTexSample>{`\
Yes, these are the ones that achieve what I showed in the pictures.

2022-03-17 20:51 UTC, jonaro00 commented on docs/contributing.mdx
> -* `build-csharp` - compiles a C#/.net version of alphaTab using the current code state
Alright. Would also like to point out that new scripts have been added since this list was last updated. Are there any that should be included?

2022-03-17 21:03 UTC, jonaro00 commented on docs/alphatex/tracks-staves.mdx
> +\\track "Second" // new track
I must admit I added the "Second" more as an experiment. The reason is that I found this:
![image](https://user-images.githubusercontent.com/54029719/158893601-72823628-6385-448f-8dfd-002744ad5869.png)
to be very confusing. It looks sort of like the First track has two tunings, since there is no track name for the second tuning. It made much more sense when I saw this:
![image](https://user-images.githubusercontent.com/54029719/158893958-9288298f-b431-4845-bb42-edf0db22c38a.png)
Maybe it's just me but the (intentionally) missing name made the example look very confusing, but perhaps this is the only way to show off the optional name. _One could argue that we could also show that the short name is optional ;)_

2022-03-17 21:08 UTC, jonaro00 commented on docs/alphatex/tracks-staves.mdx
> +\\tuning D2 A2 D3 G3 B3 E4 // tuning of new track
Ah, during the confusion described in my other comment, I didn't notice that the seven stringed tuning was actually rendered in the second track. Will fix.

This just gave me an idea though. The `Tuning` part of the docs should show an example of a non-standard amount of strings tuning. Sounds good?

2022-04-19 14:36 UTC, jonaro00 commented on docs/alphatex/bar-metadata.mdx
> +<AlphaTexSample>{`\
An alternative to backslashes everywhere would be to trim the string in the AlphaTexSample component:
`<CodeBlock>{typeof this.props.children === 'string' ? this.props.children.trim() : this.props.children}</CodeBlock>`

2022-06-12 19:14 UTC, jonaro00 commented
Reverted backslashes to instead trim strings send to `<CodeBlock>`. Added the Kotlin scripts to the list of npm scripts. Added an example of a non-standard amount of strings (5 string bass) tuning.

2022-11-06 15:35 UTC, Danielku15 requested changes
looks good mostly, just one question

2022-11-06 15:35 UTC, Danielku15 commented on docs/alphatex/tracks-staves.mdx
> -\
Have you tested that those docs pages still work? There used to be restrictions on the MDX files parser which needed backslashes here to ensure we stay in a JSX context.

2022-11-06 19:27 UTC, jonaro00 commented on docs/alphatex/tracks-staves.mdx
> -\
They look and work as expected, just like the current live site but with the leading newline removed, as shown in the PR.

2022-11-06 19:29 UTC, Danielku15 commented on docs/alphatex/tracks-staves.mdx
> -\
Great to hear. I remember participating in an issue around the MDX parser to improve the situation on not needing such hacks. Looks like things improved already.

2022-11-06 19:36 UTC, merged